name: Visual Workflow

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/void-linux/void-musl-full
      options: --privileged
      volumes:
        - /dev:/dev

    steps:
      - name: "Execute Workflow on Branch"
        run: echo "Executing abstract node execute-branch"
        env:
          branch_name: master
      - name: "Void: Prepare Container"
        run: |
          mkdir -p /etc/xbps.d && cp /usr/share/xbps.d/*-repository-*.conf /etc/xbps.d/
          sed -i 's|repo-default|repo-ci|g' /etc/xbps.d/*-repository-*.conf
          xbps-install -Syu xbps && xbps-install -yu && xbps-install -y sudo bash curl git git-lfs
          useradd -G xbuilder -M builder
      - name: "Treeless Checkout"
        uses: classabbyamp/treeless-checkout-action@v1
      - name: "Void: Prepare Masterdir"
        run: |
          chown -R builder:builder .
          sudo -Eu builder common/travis/set_mirror.sh
          sudo -Eu builder common/travis/prepare.sh
          common/travis/fetch-xtools.sh
      - name: "Void: Build Package"
        run: sudo -Eu builder ./xbps-src pkg lm_sensors
